/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.unogame;

import java.awt.Font;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author laila
 */
public class GamePanel extends javax.swing.JFrame {
private PlayerNames addPlayers = new PlayerNames();
ArrayList<String>temp=new ArrayList<>();
String[]pids;
Game game;
ArrayList<JButton>cardButtons = new ArrayList<JButton>();
ArrayList<String>cardIds;
Popup window;




    /**
     * Creates new form GamePanel
     */
public GamePanel(){}
    public GamePanel(ArrayList<String>playerIds) {
        initComponents();
        temp=playerIds;
        pids=temp.toArray(new String[temp.size()]);
        game=new Game(pids);
        populateArrayList();
        game.start(game);
        setPidName();
        topCardBtn.setIcon(new javax.swing.ImageIcon("/Users/auroba/Desktop/small/"+game.getTopcard()));
        setButtonIcons();
    }
    
    public void setButtonIcons(){
    String listString = game.getplayerhand(game.getcurrentPlayer()).stream().map(Object::toString).collect(Collectors.joining(","));
    String[] cardNames = listString.split(",");
    cardIds= new ArrayList<>(Arrays.asList(cardNames));
    for(int i=0; i<cardIds.size();i++){
        cardButtons.get(i).setIcon(new javax.swing.ImageIcon("/Users/auroba/Desktop/small/"+cardIds.get(i)+".png"));
    }
    for(int i=cardIds.size(); i<cardButtons.size();i++){
        cardButtons.get(i).setIcon(null);
    }
    }
   
    public void populateArrayList(){
    cardButtons.add(jButton1);
    cardButtons.add(jButton2);
    cardButtons.add(jButton3);
    cardButtons.add(jButton4);
    cardButtons.add(jButton5);
    cardButtons.add(jButton6);
    cardButtons.add(jButton7);
    cardButtons.add(jButton8);
    cardButtons.add(jButton9);
    cardButtons.add(jButton10);
    cardButtons.add(jButton11);
    cardButtons.add(jButton12);
    cardButtons.add(jButton13);
    cardButtons.add(jButton14);
  
    }
    public void setPidName(){
        String currentPlayer = game.getcurrentPlayer();
        pidNameLabel.setText(currentPlayer+"s Cards");
    }
    public void setPidName(String currentPlayer){
        pidNameLabel.setText(currentPlayer+"s Cards");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        downCard = new javax.swing.JButton();
        topCardBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        pidNameLabel = new javax.swing.JLabel();
        DrawCardButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Uno");

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        downCard.setIcon(new javax.swing.ImageIcon("/Users/auroba/Desktop/small/card_back.png")); // NOI18N

        topCardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topCardBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(downCard, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topCardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(609, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(topCardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(downCard, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(276, Short.MAX_VALUE))
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("jButton9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("jButton10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("jButton11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("jButton12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("jButton13");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("jButton14");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        pidNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N

        DrawCardButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        DrawCardButton.setText("Draw ");
        DrawCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrawCardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pidNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton14))
                    .addComponent(DrawCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(pidNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DrawCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DrawCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrawCardButtonActionPerformed
      JLabel message = new JLabel(game.getcurrentPlayer()+"drew a card");
      message.setFont(new Font("Arial",Font.BOLD,48));
      JOptionPane.showMessageDialog(null,message);
      try{
          game.submitdraw(game.getcurrentPlayer());
          
      }
      catch(InvalidPlayerTurnException ex){
         Logger.getLogger(GamePanel.class.getName()).log(Level.SEVERE,null,ex); 
      }
      this.setPidName(game.getcurrentPlayer());
      this.setButtonIcons();
    }//GEN-LAST:event_DrawCardButtonActionPerformed

    private void topCardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topCardBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topCardBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(cardIds.get(0)!=null){
          int index = 0;
          String cardId=cardIds.get(0);
          window= new Popup(cardId,game,index,cardButtons,this,topCardBtn);
          window.setBounds(1280,720,841,433);
          window.setVisible(true);
          window.setResizable(false);
          window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          if(cardIds.get(1)!=null){
          int index = 1;
          String cardId=cardIds.get(1);
          window= new Popup(cardId,game,index,cardButtons,this,topCardBtn);
          window.setBounds(1280,720,841,433);
          window.setVisible(true);
          window.setResizable(false);
          window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          if(cardIds.get(2)!=null){
          int index = 2;
          String cardId=cardIds.get(2);
          window= new Popup(cardId,game,index,cardButtons,this,topCardBtn);
          window.setBounds(1280,720,841,433);
          window.setVisible(true);
          window.setResizable(false);
          window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          if(cardIds.get(3)!=null){
          int index = 3;
          String cardId=cardIds.get(3);
          window= new Popup(cardId,game,index,cardButtons,this,topCardBtn);
          window.setBounds(1280,720,841,433);
          window.setVisible(true);
          window.setResizable(false);
          window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
          if(cardIds.get(4)!=null){
          int index = 4;
          String cardId=cardIds.get(4);
          window= new Popup(cardId,game,index,cardButtons,this,topCardBtn);
          window.setBounds(1280,720,841,433);
          window.setVisible(true);
          window.setResizable(false);
          window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          if(cardIds.get(5)!=null){
          int index = 5;
          String cardId=cardIds.get(5);
          window= new Popup(cardId,game,index,cardButtons,this,topCardBtn);
          window.setBounds(1280,720,841,433);
          window.setVisible(true);
          window.setResizable(false);
          window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         if(cardIds.get(6)!=null){
          int index = 6;
          String cardId=cardIds.get(6);
          window= new Popup(cardId,game,index,cardButtons,this,topCardBtn);
          window.setBounds(1280,720,841,433);
          window.setVisible(true);
          window.setResizable(false);
          window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         if(cardIds.get(7)!=null){
          int index = 7;
          String cardId=cardIds.get(7);
          window= new Popup(cardId,game,index,cardButtons,this,topCardBtn);
          window.setBounds(1280,720,841,433);
          window.setVisible(true);
          window.setResizable(false);
          window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         if(cardIds.get(8)!=null){
          int index = 8;
          String cardId=cardIds.get(8);
          window= new Popup(cardId,game,index,cardButtons,this,topCardBtn);
          window.setBounds(1280,720,841,433);
          window.setVisible(true);
          window.setResizable(false);
          window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
           if(cardIds.get(9)!=null){
          int index = 9;
          String cardId=cardIds.get(9);
          window= new Popup(cardId,game,index,cardButtons,this,topCardBtn);
          window.setBounds(1280,720,841,433);
          window.setVisible(true);
          window.setResizable(false);
          window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
          if(cardIds.get(10)!=null){
          int index = 10;
          String cardId=cardIds.get(10);
          window= new Popup(cardId,game,index,cardButtons,this,topCardBtn);
          window.setBounds(1280,720,841,433);
          window.setVisible(true);
          window.setResizable(false);
          window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
          if(cardIds.get(11)!=null){
          int index = 11;
          String cardId=cardIds.get(11);
          window= new Popup(cardId,game,index,cardButtons,this,topCardBtn);
          window.setBounds(1280,720,841,433);
          window.setVisible(true);
          window.setResizable(false);
          window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
          if(cardIds.get(12)!=null){
          int index = 12;
          String cardId=cardIds.get(12);
          window= new Popup(cardId,game,index,cardButtons,this,topCardBtn);
          window.setBounds(1280,720,841,433);
          window.setVisible(true);
          window.setResizable(false);
          window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
          if(cardIds.get(13)!=null){
          int index = 13;
          String cardId=cardIds.get(13);
          window= new Popup(cardId,game,index,cardButtons,this,topCardBtn);
          window.setBounds(1280,720,841,433);
          window.setVisible(true);
          window.setResizable(false);
          window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      }
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DrawCardButton;
    private javax.swing.JButton downCard;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pidNameLabel;
    private javax.swing.JButton topCardBtn;
    // End of variables declaration//GEN-END:variables
}

