/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.unogame;

import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author laila
 */
public class PickColorFrame extends javax.swing.JFrame {

   private unoCards.cardColor wildColor = null;
   Boolean allow = false;
   Popup popup;
    public PickColorFrame() {
        initComponents();
    }
    public PickColorFrame(Popup pop){
        initComponents();
        popup = pop;
    }
    public unoCards.cardColor choseColor(unoCards card){
        if(card.getcardColor()==unoCards.cardColor.wild){
            this.setVisible(true);
            this.setResizable(false);
            this.setBounds(100,150,600,700);
        }
        return card.getcardColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        redbtn = new javax.swing.JButton();
        bluebtn = new javax.swing.JButton();
        greenbtn = new javax.swing.JButton();
        yelloebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Pick Color Of Wild Card");

        redbtn.setText("Red");
        redbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redbtnActionPerformed(evt);
            }
        });

        bluebtn.setText("Blue");
        bluebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bluebtnActionPerformed(evt);
            }
        });

        greenbtn.setText("Green");
        greenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenbtnActionPerformed(evt);
            }
        });

        yelloebtn.setText("Yellow");
        yelloebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yelloebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bluebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(greenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yelloebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(redbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bluebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(greenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yelloebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void greenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenbtnActionPerformed
       wildColor=unoCards.cardColor.green;
      JLabel message = new JLabel("Wild card color is green");
      message.setFont(new Font("Arial",Font.BOLD,48));
      JOptionPane.showMessageDialog(null,message);
      allow=true;
      this.dispose();
      popup.declaredColor=unoCards.cardColor.green;
      popup.gamePanel.setPidName(popup.game.getcurrentPlayer());
      popup.gamePanel.setButtonIcons();
      popup.topCardBtn.setIcon(new javax.swing.ImageIcon("/Users/auroba/NetBeansProjects/UnoGame/src/main/java/com/mycompany/unogame/small/"+popup.game.getTopcardImage()));
      popup.game.setcardcolor(unoCards.cardColor.green);
      popup.dispose();
    }//GEN-LAST:event_greenbtnActionPerformed

    private void redbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redbtnActionPerformed
      wildColor=unoCards.cardColor.red;
      JLabel message = new JLabel("Wild card color is red");
      message.setFont(new Font("Arial",Font.BOLD,48));
      JOptionPane.showMessageDialog(null,message);
      allow=true;
      this.dispose();
      popup.declaredColor=unoCards.cardColor.red;
      popup.gamePanel.setPidName(popup.game.getcurrentPlayer());
      popup.gamePanel.setButtonIcons();
      popup.topCardBtn.setIcon(new javax.swing.ImageIcon("/Users/auroba/NetBeansProjects/UnoGame/src/main/java/com/mycompany/unogame/small/"+popup.game.getTopcardImage()));
      popup.game.setcardcolor(unoCards.cardColor.red);
      popup.dispose();
    }//GEN-LAST:event_redbtnActionPerformed

    private void bluebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bluebtnActionPerformed
        wildColor=unoCards.cardColor.blue;
      JLabel message = new JLabel("Wild card color is blue");
      message.setFont(new Font("Arial",Font.BOLD,48));
      JOptionPane.showMessageDialog(null,message);
      allow=true;
      this.dispose();
      popup.declaredColor=unoCards.cardColor.blue;
      popup.gamePanel.setPidName(popup.game.getcurrentPlayer());
      popup.gamePanel.setButtonIcons();
      popup.topCardBtn.setIcon(new javax.swing.ImageIcon("/Users/auroba/NetBeansProjects/UnoGame/src/main/java/com/mycompany/unogame/small/"+popup.game.getTopcardImage()));
      popup.game.setcardcolor(unoCards.cardColor.blue);
      popup.dispose();
    }//GEN-LAST:event_bluebtnActionPerformed

    private void yelloebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yelloebtnActionPerformed
       wildColor=unoCards.cardColor.yellow;
      JLabel message = new JLabel("Wild card color is yellow");
      message.setFont(new Font("Arial",Font.BOLD,48));
      JOptionPane.showMessageDialog(null,message);
      allow=true;
      this.dispose();
      popup.declaredColor=unoCards.cardColor.yellow;
      popup.gamePanel.setPidName(popup.game.getcurrentPlayer());
      popup.gamePanel.setButtonIcons();
      popup.topCardBtn.setIcon(new javax.swing.ImageIcon("/Users/auroba/NetBeansProjects/UnoGame/src/main/java/com/mycompany/unogame/small/"+popup.game.getTopcardImage()));
      popup.game.setcardcolor(unoCards.cardColor.yellow);
      popup.dispose();
    }//GEN-LAST:event_yelloebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickColorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bluebtn;
    private javax.swing.JButton greenbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton redbtn;
    private javax.swing.JButton yelloebtn;
    // End of variables declaration//GEN-END:variables
}

